describe('E2E Tests - Pay', () => {
    it('Should log into application', () => {
        browser.url('http://zero.webappsecurity.com/')
        $('#signin_button').waitForExist()
        $('#signin_button').click()
        $('#login_form').waitForExist()
        $('#user_login').setValue('username')
        $('#user_password').setValue('password')
        $('input[type= "submit"]').waitForExist()
        $('input[type= "submit"]').click()
        $('.nav-tabs').waitForExist()
    })
    it('Should make payment', () => {
        $('#pay_bills_tab').waitForExist()
        $('#pay_bills_tab').click()
        const payee= $('#sp_payee')
        payee.waitForExist()
        payee.selectByAttribute('value', 'apple')
        const account = $('#sp_account')
        account.waitForExist()
        account.selectByVisibleText('Loan')
        const ammount = $('#sp_amount')
        ammount.waitForExist()
        ammount.setValue('1000')
        const date = $('#sp_date')
        date.waitForExist()
        date.setValue('2020-08-27')
        const description = $('#sp_description')
        description.waitForExist()
        description.setValue('Money payment')
        const payBtn = $('#pay_saved_payees')
        payBtn.waitForExist()
        payBtn.click()
        const successAlert = $('#alert_content')
        expect(successAlert).toHaveText('The payment was successfully submitted.')
    })
})